Pomo/temporal experiment
C4T-BuT-S4D/FastAD pull request #1
Opened 2023-09-20 14:22 UTC by pomo-mondreganto

2023-10-02 22:06 UTC, jnovikov requested changes

2023-10-02 22:06 UTC, jnovikov commented on Makefile
> +commit-proto: proto
Немного кринге. Я бы хотя бы не делал коммит.

2023-10-02 22:06 UTC, jnovikov commented on cmd/checkers/main.go
> +	servicespb "github.com/c4t-but-s4d/fastad/pkg/proto/data/services"
Добавь линтер из нео.

2023-10-02 22:06 UTC, jnovikov commented on internal/checkers/activity_state.go
> +	ActivityFetchDataName = "ActivityFetchData"
Шо за Java.

2023-10-02 22:06 UTC, jnovikov commented on cmd/checkers/main.go
> +	checkersWorker := worker.New(temporalClient, "checkers", worker.Options{})
Мне не очень нравится как сейчас разделено создание activity и workflow.

По-сути тут нет логики и понять что тут происходит без чтения internal/checkers невозможно.

Предлагаю либо здесь заинлайнить константы и создание WorkFlow, либо создание/конфигураци воркера тоже положить в internal/checkers

2023-10-02 22:06 UTC, jnovikov commented on internal/checkers/activity_state.go
> +	ActivityFetchDataName = "ActivityFetchData"
В плане если эти константы можно заинлайнить (применить в одном файле), то лучше так сделать.

2023-10-02 22:06 UTC, jnovikov commented on internal/checkers/activity_put.go
> +func (s *ActivityState) PutActivityDefinition(ctx context.Context, params *PutActivityParameters) (*PutActivityResult, error) {
PutActivityDefinition ничего не говорит о том, что будет происходить.

Давай назовем PutFlags()

2023-10-02 22:06 UTC, jnovikov commented on internal/checkers/config.go
> +	Address string `mapstructure:"address"`
Кажется в DataService будут и другие ходить. 

Хорошо было бы отдельно сделать конфиги под эти сервисы.

Условно DataServiceClientConfig struct

2023-10-02 22:06 UTC, jnovikov commented on internal/checkers/config.go
> +type Temporal struct {
Это тоже кажется будет много где юзаться.

2023-10-02 22:06 UTC, jnovikov commented on internal/checkers/activity_last.go
> +type LastActivityParameters struct {
Я вообще не понимаю о чем это.

2023-10-02 22:06 UTC, jnovikov commented on internal/checkers/actions.go
> +func RunCheckAction(
Кажется можно большинство этих функций вынести в их activity (чтобы функции не зависили от activityParameters), а тут оставить только generic-логику.

2023-10-02 22:06 UTC, jnovikov commented on internal/checkers/activity_check.go
> +func (s *ActivityState) CheckActivityDefinition(ctx context.Context, params *CheckActivityParameters) (*CheckActivityResult, error) {
Можно еще во все activity добавить heartbeat https://legacy-documentation-sdks.temporal.io/go/heartbeat-an-activity

(Могу сделать потом)

2023-10-02 22:06 UTC, jnovikov commented on internal/checkers/utils.go
> +	err := cmd.Start()
Кажется можно все это заменить на 

cmd := exec.CommandContext(ctx, ...)
cmd.Cancel = func() error {
  if err := cmd.Process.Signal(syscall.SIGTERM); err != nil {
	logrus.Debugf("failed to send SIGTERM to process: %s", err)
  }
  t := time.NewTimer(killDelay)
  defer t.Stop()
...
  
  
}

2023-10-02 22:06 UTC, jnovikov commented on internal/checkers/utils.go
> +		if err != nil {
Зачем? Хотя все-равно предлагаю просто cancel() поменять.

2023-10-02 22:06 UTC, jnovikov commented on internal/checkers/workflow.go
> +		ScheduleToCloseTimeout: time.Second * 3,
А мы не хотим везде правильные timeout'ы навесить на всякий ?

2023-10-02 22:06 UTC, jnovikov commented on cmd/fastad/cli/setup/checker_action.go
> +func (a CheckerAction) Validate() error {
Я бы тогда сделал New(s string) (CheckerAction, error)

2023-10-02 22:06 UTC, jnovikov commented on cmd/fastad/cli/setup/checker_action.go
> +type CheckerAction string
Можно сделать 
type CheckAction {
  action string
}

Чтобы нельзя было сделать невалидный.

2023-10-02 22:06 UTC, jnovikov commented on cmd/fastad/cli/common/context.go
> +type CommandContext struct {
?

2023-10-02 22:06 UTC, jnovikov commented on cmd/data_service/main.go
> +	sqlDB := sql.OpenDB(pgConn)
inline

2023-10-02 22:06 UTC, jnovikov commented on cmd/data_service/main.go
> +	pgConn := pgdriver.NewConnector(
Это пул же ? Не нужно будет делать реконнект ?

2023-10-02 22:06 UTC, jnovikov commented on cmd/fastad/cli/setup/checker_type.go
> +		return checkerpb.Type_TYPE_LEGACY
Я вообще за то, чтобы конфижить протобафами везде.

В плане сделать просто FromStr() -> checkerpb.Type, и ToStr(), тогда не нужно будет делать свой тип.

2023-10-02 22:06 UTC, jnovikov commented on pkg/grpctools/client.go
Я не очень люблю *tools, но тут пока мало кода, так что норм.

(Вообще полезно тогда разнести на grpcclient, grpcserver)

2023-10-02 22:06 UTC, jnovikov commented on proto/data/game_state/game_state.proto
> +    uint32 total_rounds = 3;
Мб сделать oneof { end_time, total_rounds} ? 

Кажется нет смысла в обоих опциях ?

2023-10-02 22:06 UTC, jnovikov commented on proto/data/game_state/game_state.proto
> +    uint32 flag_lifetime_rounds = 5;
Мне кажется полезно сразу разделить на GameConfig и GameState.

start_time, end_time, total_rounds, flag_lifetime_rounds, mode, round_duration - config
Остальное - state.

2023-10-02 22:06 UTC, jnovikov commented on proto/data/game_state/game_state.proto
> +    data.version.Version version = 1;
А в чем тут идея ? Мы хотим состояние игры версионировать ? Тогда версия тут должна быть optional ?

2023-10-02 22:06 UTC, jnovikov commented on proto/data/game_state/game_state.proto
> +    google.protobuf.Timestamp start_time = 1;
Если сделать как я предложил с конфигом, то тут будет просто конфиг новый.

2023-10-02 22:06 UTC, jnovikov commented on proto/data/game_state/game_state.proto
> +    google.protobuf.Timestamp start_time = 1;
Можно еще сделать c FieldMask:
https://netflixtechblog.com/practical-api-design-at-netflix-part-1-using-protobuf-fieldmask-35cfdc606518

2023-10-02 22:06 UTC, jnovikov commented on proto/data/services/services.proto
> +message CreateBatchRequest {
Я бы переименовал на CreateRequest, если сразу делаем BatchApi, то норм.

2023-10-02 22:06 UTC, jnovikov commented on proto/data/teams/teams.proto
> +    map<string, string> labels = 5;
Что это ?

2023-10-02 22:06 UTC, jnovikov commented on proto/data/teams/teams.proto
> +    int32 id = 1;
Давай сразу avatar поддержим ? Или сделаем отдельно сервис для Avatar by ID ?

2023-10-02 22:06 UTC, jnovikov commented on proto/data/teams/teams.proto
> +    string token = 4;
Может token отдельно вынести ?

2023-10-02 22:06 UTC, jnovikov commented on proto/data/teams/teams.proto
> +    string address = 3;
Тут надо подумать. Вдруг мы захотим как хакердом делать разный адрес, в зависимости от сервиса ?

2023-10-02 22:06 UTC, jnovikov commented on proto/data/version/version.proto
> +message Version {
Мы правда хотим для всего делать версии ? Если да, то предлагается старые просто хранить ?

2023-10-02 22:06 UTC, jnovikov commented on internal/models/checker_execution.go
> +	TSSHistoryEntryID int `bun:"tss_history_entry_id,notnull"`
Who is TSS ?

2023-10-02 22:06 UTC, jnovikov commented on internal/models/checker_execution.go
> +type CheckerExecution struct {
Это модель под весь запуск чекера ? Мы не хотим внутри еще отдельно залогать что выполнилось, а что нет ?

2023-10-02 22:06 UTC, jnovikov commented on internal/models/checker_verdict.go
> +type CheckerVerdict struct {
Чет мне не оч что это называется Вердикт. 

Кажется вердикт за раунд == комбинация N вердиктов на самом деле.

2023-10-02 22:06 UTC, jnovikov commented on internal/models/checker_verdict.go
> +func (v *CheckerVerdict) String() string {
Я бы убрал pointer-reciever если можно.

2023-10-02 22:06 UTC, jnovikov commented on internal/models/flag.go
> +	Public  string
Добавь коммент про Public и Private часть.

2023-10-02 22:06 UTC, jnovikov commented on internal/models/game.go
> +	StartTime   time.Time  `bun:"start_time,notnull"`
Тут тоже можно подумать не разделить ли нам конфиг и стейт.

2023-10-02 22:06 UTC, jnovikov commented on internal/models/game.go
> +func NewGameStateFromProto(p *gspb.GameState) *GameState {
FromProto()

2023-10-02 22:06 UTC, jnovikov commented on internal/models/service.go
> +	DefaultScore float64 `bun:"default_score,notnull"`
Мы точно хотим это хранить ?

2023-10-02 22:06 UTC, jnovikov commented on internal/models/service.go
> +	DefaultScore float64 `bun:"default_score,notnull"`
В плане кажется это нужно только при создании игры.

2023-10-02 22:06 UTC, jnovikov commented on internal/models/service.go
> +	Actions        map[checkerpb.Action]*ServiceActionConfig `bun:"actions,notnull"`
А как он такое в PG хранит ?

2023-10-02 22:06 UTC, jnovikov commented on internal/models/tss_history_entry.go
> +	Checks int `bun:"checks"`
Это сколько Checks было запущено ?

2023-10-02 22:06 UTC, jnovikov commented on internal/models/tss_history_entry.go
> +type TSSHistoryEntry struct {
Я бы раскрыл TSS

2023-10-02 22:06 UTC, jnovikov commented on internal/models/version.go
> +type Version struct {
Версия глобальная что ли ?

2023-10-02 22:06 UTC, jnovikov commented on internal/models/version.go
> +type Version struct {
Если нет, то нужно где-то коммент написать про версии.

2023-10-02 22:06 UTC, jnovikov commented on front/README.md
> +# React + TypeScript + Vite
Точно хотим React ?

2023-10-02 22:06 UTC, jnovikov commented on internal/models/service.go
> +func (s *Service) RunCount(action checkerpb.Action) int {
Тут наверное было бы хорошо сделать GetRunCount в качестве исключения.

В контексте чекера RunCount() звучит как запустить подсчет.

2023-10-02 22:06 UTC, jnovikov commented on internal/models/service.go
> +	DefaultScore float64 `bun:"default_score,notnull"`
В плане можно же очки класть как снэпшот очков изначальный.

2023-10-02 22:06 UTC, jnovikov commented on internal/checkers/workflow.go
> +			workflow.Go(putActivityCtx, func(ctx workflow.Context) {
Мы точно хотим это параллелить ? Как сейчас в форкаде ?

2023-10-02 22:06 UTC, jnovikov commented on internal/checkers/workflow.go
> +
Тут надо тоже TODO на vulns добавить.

2023-10-02 22:06 UTC, jnovikov commented on internal/checkers/workflow.go
Неплохо смотрится даже как воркфлоу.

2023-10-02 22:06 UTC, jnovikov commented on internal/clients/gamestate/client.go
> +	resp, err := c.c.Get(ctx, &gspb.GetRequest{Version: c.version})
Чет я не очень понял зачем, учитывая что получить версию по перфу == получить стэйт, не ? 

Не легче внутри самого сервиса тогда сделать кэш ? И всегда в него ходить ?

Или тогда уже сделать Stream и обновления слушать.

2023-10-02 22:06 UTC, jnovikov commented on internal/clients/services/client.go
> +func (c *Client) refresh(ctx context.Context) error {
Тот же вопрос.

2023-10-02 22:06 UTC, jnovikov commented on internal/clients/teams/cache.go
> +type Cache struct {
Кажется это можно было бы сделать generic'ом?

2023-10-02 22:06 UTC, jnovikov commented on cmd/fastad/cli/setup/setup.go
> +			createdGameService, err := gameStateClient.Update(c.Context, cfg.Game.ToUpdateRequestProto())
Тут тоже вопрос про батч очков и вообще нужно ли тут очки затирать.

2023-10-02 22:06 UTC, jnovikov commented on cmd/fastad/main.go
А мы хотим fastad как single-entry ?

Я просто думаю не сделать ли нам условно ./fastad как клиент, и отдельно ./fastad-server ?

2023-10-02 22:06 UTC, jnovikov commented on cmd/receiver/main.go
> +	logging.Init()
Можно тут еще grpchelper заюзать.

2023-10-02 22:06 UTC, jnovikov commented on cmd/ticker/main.go
> +		HostPort: "localhost:7233",
Сделай конфиг сразу ?

2023-10-02 22:06 UTC, jnovikov commented on internal/services/gamestate/controller.go
> +func (c *Controller) Update(ctx context.Context, req *gspb.UpdateRequest) (*models.GameState, error) {
Давай pause отдельно сделаем ?

2023-10-02 22:06 UTC, jnovikov commented on internal/version/controller.go
> +	if errors.Is(err, sql.ErrNoRows) {
Если делать версии, то кажется отсутствие версии должно быть ошибкой.

2023-10-02 22:06 UTC, jnovikov commented on internal/ticker/ticker.go
> +	workflowOptions := client.StartWorkflowOptions{
inline

2023-10-02 22:06 UTC, jnovikov commented on internal/ticker/ticker.go
> +	t.RunOnce(ctx)
Тут легкий кринж, что второй раунд начнется с задержкой получается.

2023-10-02 22:06 UTC, jnovikov commented on internal/ticker/ticker.go
> +	t.RunOnce(ctx)
Наверное в случае если мы внутри RunOnce() будем проверять гейм-стейт (paused,started), то пофиг.

2023-10-02 22:06 UTC, jnovikov commented on internal/services/teams/service.go
> +		teamModel.Token = uuid.NewString()
Я бы вынес сразу в интерфейс/функу, вдруг мы захотим JWT ?

(А JWT звучит хорошо так-то).

2023-10-02 22:06 UTC, jnovikov commented on internal/services/teams/service.go
> +		return &teamspb.ListResponse{Version: version.NewVersionProto(gotVersion)}, nil
А почему пустой ответ на текущей версии ?

2023-10-02 22:06 UTC, jnovikov commented on internal/services/teams/service.go
> +	// FIXME: check admin rights, remove token from result.
Если токены отдельно сохраним, то проще будет кажется.

2023-10-02 22:06 UTC, jnovikov commented on internal/services/teams/sanitize.go
> +func (s *Service) sanitizeCreateBatchRequest(req *teamspb.CreateBatchRequest) error {
Это валидация кажется, а не санитизация.

2023-10-02 22:06 UTC, jnovikov commented on internal/services/services/sanitize.go
validate

2023-10-02 22:06 UTC, jnovikov commented on internal/services/services/sanitize.go
https://github.com/bufbuild/protoc-gen-validate ?

2023-10-02 22:06 UTC, jnovikov commented on internal/services/gamestate/controller.go
> +	if req.EndTime != nil {
А TotalRounds мб тогда тоже можно не передавать ?

2023-10-03 12:22 UTC, pomo-mondreganto commented on cmd/checkers/main.go
> +	servicespb "github.com/c4t-but-s4d/fastad/pkg/proto/data/services"
Я, вроде, все линтеры перенес, какого не хватает?

2023-10-03 12:31 UTC, pomo-mondreganto commented on internal/checkers/workflow.go
> +		ScheduleToCloseTimeout: time.Second * 3,
Они уже правильные

2023-10-03 12:33 UTC, pomo-mondreganto commented on cmd/fastad/cli/setup/checker_action.go
> +type CheckerAction string
Эта структура используется только в конфиге (собственно, она лежит в cmd папке). Она должна парситься из yaml, для этого надо будет для кастомной структуры писать Unmarshal методы, что в целом то же самое, что и просто позвать validate

2023-10-03 12:34 UTC, pomo-mondreganto commented on cmd/fastad/cli/common/context.go
> +type CommandContext struct {
Нужен будет конфиг, трейсинг, ещё что-нибудь. Будем в эту структуру добавлять. На самом деле она исчезнет при переписывании на cobra (см todo), поэтому это уже легаси...

2023-10-03 12:36 UTC, pomo-mondreganto commented on cmd/data_service/main.go
> +	pgConn := pgdriver.NewConnector(
Неа, надо будет починить

2023-10-03 12:36 UTC, pomo-mondreganto commented on cmd/fastad/cli/setup/checker_type.go
> +		return checkerpb.Type_TYPE_LEGACY
Из коробки не сработает, всё равно придется делать тип, чтобы unmarshal переопределить. В целом нормальный вариант, бойлерплейта чуть поменьше будет

2023-10-03 12:37 UTC, pomo-mondreganto commented on proto/data/game_state/game_state.proto
> +    uint32 total_rounds = 3;
Почему бы и нет, дополнительную валидацию нет смысла добавлять, кажется (и на уровне базы оно всё равно будет не oneof)

2023-10-03 12:38 UTC, pomo-mondreganto commented on proto/data/game_state/game_state.proto
> +    data.version.Version version = 1;
Мы хотим все модели версионировать для client-side cache, чтобы не фетчить из базы модели, если у клиента уже достаточно актуальная версия

2023-10-03 12:39 UTC, pomo-mondreganto commented on proto/data/services/services.proto
> +message CreateBatchRequest {
Будет ещё create single, когда будет админка

2023-10-03 12:39 UTC, pomo-mondreganto commented on proto/data/teams/teams.proto
> +    int32 id = 1;
Будет отдельный сервис для хранения аватаров, но метаданные хочется в одном месте хранить (здесь), но давай попозже добавим

2023-10-03 12:40 UTC, pomo-mondreganto commented on proto/data/teams/teams.proto
> +    int32 id = 1;
Не приоритет, а поле добавить легко

2023-10-03 12:40 UTC, pomo-mondreganto commented on proto/data/teams/teams.proto
> +    string token = 4;
Зачем?

2023-10-03 12:41 UTC, pomo-mondreganto commented on proto/data/teams/teams.proto
> +    string address = 3;
Сделаем как обычно, * в месте, где надо заменить на название/октет/etc, в чекере заменим. Можно поддержать какие-нибудь `{{ .Service }}` или `{{ .ServiceID }}` (и gotemplate делать), но это не поменяет формат тут (всё ещё строчка)

2023-10-03 12:41 UTC, pomo-mondreganto commented on internal/models/checker_execution.go
> +	TSSHistoryEntryID int `bun:"tss_history_entry_id,notnull"`
TeamServiceState (не придумал название лучше, условно это одна клеточка скорборда)

2023-10-03 12:42 UTC, pomo-mondreganto commented on proto/data/version/version.proto
> +message Version {
Мы нигде не храним версии, это для клиентского кеша

2023-10-03 12:42 UTC, pomo-mondreganto commented on internal/models/checker_execution.go
> +type CheckerExecution struct {
Модель на одно выполнение exec/Cmd

2023-10-03 12:43 UTC, pomo-mondreganto commented on internal/models/checker_verdict.go
> +type CheckerVerdict struct {
У нас есть и то, и другое, можно отдельную структуру завести

2023-10-03 12:43 UTC, pomo-mondreganto commented on internal/models/checker_verdict.go
> +func (v *CheckerVerdict) String() string {
Мне всё ещё лень думать над pointer/value receiver (и тем более переделывать value receiver, когда появляется pointer receiver, потому что одновременно нельзя по кодстайлу)

2023-10-03 12:44 UTC, pomo-mondreganto commented on internal/models/game.go
> +	StartTime   time.Time  `bun:"start_time,notnull"`
Я думал, понял, что в стейте только round+round_start, плюс почти везде нужен и config, и state (при этом config ещё и меняться умеет весь)

2023-10-03 12:44 UTC, pomo-mondreganto commented on internal/models/game.go
> +func NewGameStateFromProto(p *gspb.GameState) *GameState {
Не понял

2023-10-03 12:45 UTC, pomo-mondreganto commented on internal/models/service.go
> +	DefaultScore float64 `bun:"default_score,notnull"`
Когда ты новый сервис добавляешь, это поле в любом случае нужно

2023-10-03 12:45 UTC, pomo-mondreganto commented on internal/models/service.go
> +	DefaultScore float64 `bun:"default_score,notnull"`
Новый сервис или новую команду*

2023-10-03 12:46 UTC, pomo-mondreganto commented on internal/models/service.go
> +	Actions        map[checkerpb.Action]*ServiceActionConfig `bun:"actions,notnull"`
jsonb (но стоит явно написать это, думаю)

2023-10-03 12:46 UTC, pomo-mondreganto commented on internal/models/tss_history_entry.go
> +	Checks int `bun:"checks"`
Да, в old модели SLA = checks_passed / checks

2023-10-03 12:47 UTC, pomo-mondreganto commented on internal/models/tss_history_entry.go
> +type TSSHistoryEntry struct {
Слишком вербоузно получается (`TeamServiceStateHistoryEntry`)

2023-10-03 12:48 UTC, pomo-mondreganto commented on internal/models/version.go
> +type Version struct {
У версии есть name модели (при таком подходе удобно версионировать разные модели)

2023-10-03 12:49 UTC, pomo-mondreganto commented on front/README.md
> +# React + TypeScript + Vite
Точно не хотим vue

2023-10-03 12:49 UTC, pomo-mondreganto commented on front/README.md
> +# React + TypeScript + Vite
(а больше ничего не существует)

2023-10-03 12:51 UTC, pomo-mondreganto commented on internal/checkers/workflow.go
> +			workflow.Go(putActivityCtx, func(ctx workflow.Context) {
Параллельно, и точно хотим параллелить (иначе 2 пута/гета с долгим чекером не запустить, а грузят они обычно ядра слабо)

2023-10-03 12:52 UTC, pomo-mondreganto commented on internal/clients/gamestate/client.go
> +	resp, err := c.c.Get(ctx, &gspb.GetRequest{Version: c.version})
Достать из базы 200 команд не так же по нагрузке, как достать 1 число. Сделать кеш внутри сервиса тоже можно, двухуровневый кеш никто не мешает иметь (клиентский при этом хорош тем, что убирает сетевую задержку и пишется совсем просто)

2023-10-03 12:52 UTC, pomo-mondreganto commented on internal/clients/gamestate/client.go
> +	resp, err := c.c.Get(ctx, &gspb.GetRequest{Version: c.version})
Серверный кеш должен уметь сложные вещи (между репликами синхронизироваться как минимум)

2023-10-03 12:53 UTC, pomo-mondreganto commented on internal/clients/teams/cache.go
> +type Cache struct {
Нельзя, разные кеши разный паттерн доступа могут иметь (service by id, team by id, flag by text, etc)

2023-10-03 12:54 UTC, pomo-mondreganto commented on cmd/fastad/cli/setup/setup.go
> +			createdGameService, err := gameStateClient.Update(c.Context, cfg.Game.ToUpdateRequestProto())
Не понял

2023-10-03 12:55 UTC, pomo-mondreganto commented on cmd/fastad/main.go
Это будет cli для управления сервисом (+ у каждого микросервиса свой endpoint, сейчас есть checkers, ticker и data-service)

2023-10-03 12:55 UTC, pomo-mondreganto commented on cmd/receiver/main.go
> +	logging.Init()
Кого?

2023-10-03 12:57 UTC, pomo-mondreganto commented on internal/version/controller.go
> +	if errors.Is(err, sql.ErrNoRows) {
Отсутствие версии происходит, когда команды/сервисы ещё не успели создать (до инициализации фастада из cli), можно и ошибку возвращать, кажется, не принципиально. Ещё можно version = 0 при миграции всем типам модели поставить и возвращать тут ошибку.

2023-10-03 12:58 UTC, pomo-mondreganto commented on internal/ticker/ticker.go
> +	t.RunOnce(ctx)
да, это просто демка сервиса, чтобы локально чекеры иметь возможность запускать. Потом будет run каждую секунду, который проверяет last run в базе и interval и если прошел раунд, шедулит новый раунд

2023-10-03 12:58 UTC, pomo-mondreganto commented on internal/services/teams/service.go
> +		return &teamspb.ListResponse{Version: version.NewVersionProto(gotVersion)}, nil
Потому что это подразумевает, что клиент уже имеет данные этой версии

2023-10-03 12:59 UTC, pomo-mondreganto commented on internal/services/teams/sanitize.go
> +func (s *Service) sanitizeCreateBatchRequest(req *teamspb.CreateBatchRequest) error {
Это и то, и то, можно validate назвать

2023-10-03 13:00 UTC, pomo-mondreganto commented on internal/services/services/sanitize.go
Я кринжую с этой библиотеки и её формата, мне проще кодом валидацию написать

2023-10-03 13:01 UTC, pomo-mondreganto commented on internal/services/gamestate/controller.go
> +	if req.EndTime != nil {
Писал выше, нет смысла ограничивать (потребовать хотя бы одно из них достаточно)

2023-10-04 02:26 UTC, pomo-mondreganto commented on Makefile
> +commit-proto: proto
Для этого есть просто proto, задача commit-proto как раз сделать commit, и нужно это мне, потому что лень настраивать IDE так, чтобы он не переформатировал мне автосгенеренные .ts файлики (тем более что фронт я буду в vscode писать)

2023-10-04 02:27 UTC, pomo-mondreganto commented on internal/services/teams/service.go
> +	// FIXME: check admin rights, remove token from result.
Хранить токены отдельно не проще само по себе, надо как минимум отдельную апишку для них делать, а это точно делать лень

2023-10-04 02:28 UTC, pomo-mondreganto commented on proto/data/teams/teams.proto
> +    map<string, string> labels = 5;
способ расширять фронт (в форкаде есть bool highlighted) + возможность навесить какие-то теги для команды, полезно на фронте (если когда-нибудь будем делать отдельные зачеты, например)

2023-10-04 02:29 UTC, pomo-mondreganto commented on cmd/fastad/cli/setup/checker_action.go
> +func (a CheckerAction) Validate() error {
Не решает задачу парсинга из yaml, ради которой этот тип существует

2023-10-04 02:30 UTC, pomo-mondreganto commented on internal/checkers/activity_check.go
> +func (s *ActivityState) CheckActivityDefinition(ctx context.Context, params *CheckActivityParameters) (*CheckActivityResult, error) {
Я читал, надо на всё навесить, но потом

2023-10-04 02:31 UTC, pomo-mondreganto commented on internal/checkers/actions.go
> +func RunCheckAction(
Этот набор функций, скорее всего, будет меняться вместе (как минимум put + get всегда должны меняться вместе), поэтому удобнее их иметь в одном файле. В activity будет больше кода про сетап аргументов для этих функций (сгенерировать флаг, положить его в базу, etc)

2023-10-04 02:37 UTC, pomo-mondreganto commented on proto/data/game_state/game_state.proto
> +    google.protobuf.Timestamp start_time = 1;
Норм вариант, но не звучит как часть mvp. Разделить config на state + config с 3 полями в целом можно (+ я подумал и понял, что у них должны быть разные варианты кеширования, config надо кешировать более агрессивно, чем state, который меняется часто)

2023-10-04 02:37 UTC, pomo-mondreganto commented on proto/data/game_state/game_state.proto
> +    uint32 flag_lifetime_rounds = 5;
Ответил ниже

2023-10-04 02:38 UTC, pomo-mondreganto commented on internal/models/checker_verdict.go
> +type CheckerVerdict struct {
Но эта структура всё ещё останется CheckerVerdict, вторая просто будет называться RoundVerdict

2023-10-04 02:38 UTC, pomo-mondreganto commented on internal/models/checker_verdict.go
> +type CheckerVerdict struct {
Ещё надо подумать, как нормально делать RoundVerdict в такой модели, когда у нас есть не привязанные к раунду actions (как это в блице в форкаде сейчас)

2023-10-04 02:40 UTC, pomo-mondreganto commented on internal/checkers/workflow.go
> +
Тут как минимум надо флаг генерировать, потом

2023-10-04 11:56 UTC, pomo-mondreganto commented on cmd/data_service/main.go
> +	pgConn := pgdriver.NewConnector(
Посмотрел ещё раз, это коннектор, создающий один коннект, пул есть в дефолтном sql.DB

2023-10-04 12:30 UTC, pomo-mondreganto commented on internal/models/flag.go
> +	Public  string
Передумал, не хочу тут писать полотно про то, что там бывает в PUT и GET (про это имхо должна быть страничка на вики, а не комментарии в коде)

2023-10-04 12:31 UTC, pomo-mondreganto commented on internal/models/flag.go
> +	Public  string
А кроме этого сюда нечего написать, кроме того, что public можно/нужно давать игрокам, а private нет...

2023-10-04 12:35 UTC, pomo-mondreganto commented on internal/services/teams/service.go
> +		teamModel.Token = uuid.NewString()
Написал тудушку, потом, когда у сервера будет pk (и admin api, чтобы его получить), добавлю

2023-10-04 15:04 UTC, pomo-mondreganto commented on cmd/receiver/main.go
> +	logging.Init()
На этот файл можно не смотреть, он был написан до всех остальных и будет полностью переписан позже (когда появится private key для флагов, не раньше)

2023-10-04 21:02 UTC, jnovikov requested changes
И некоторые issue закрыты без изменений кода (например Cancel())

2023-10-04 21:02 UTC, jnovikov commented on cmd/checkers/main.go
> +	servicespb "github.com/c4t-but-s4d/fastad/pkg/proto/data/services"
Я про группировку импортов (мне казалось ты делал такой)

2023-10-04 21:02 UTC, jnovikov commented on cmd/data_service/main.go
> +	sqlDB := sql.OpenDB(pgConn)
Можно тоже заинлайнить вроде

2023-10-04 21:02 UTC, jnovikov commented on internal/services/teams/service.go
> +		return &teamspb.ListResponse{Version: version.NewVersionProto(gotVersion)}, nil
Мне кажется если ты хочешь делать такую семантику, то лучше ее прям отдельно в протобаф добавить:

Условно сделать ListResponse{
  oneof {
    NO_UPDATE = 1;
    Response = 2;
    }

2024-12-23 18:25 UTC, closed without merging